### ISSUE TITLE
Fix autoRename not working on instances

### ISSUE THREAD

**Issue by megaroeny** [megaroeny/Figma-Reset-Text-Layer-Name#1]
**Describe the bug**
The plugin no longer works on component instances for some reason...

**To Reproduce**
1. Select a text layer in a component instance
2. The confirmation snackbar appears, but in the console, there is a warning and it doesn't actually work

**Expected behavior**
Should reset layer names inside instances too

**Screenshots or GIFs**
![image](https://user-images.githubusercontent.com/1559447/114217349-08366b80-9936-11eb-8ca5-5c135f222375.png)

**Additional context**
Need to try to get the latest API version, currently not updating past v14 for some reason.

**Comment by tank666** [comment]
You can fix the plugin's functionality like this:
`node.name = "";`
Paste this code instead of `node.autoRename = true;`

**Comment by megaroeny** [comment]
> You can fix the plugin's functionality like this:
> `node.name = "";`
> Paste this code instead of `node.autoRename = true;`

Holy cow, that's what I initially had when I first published this plugin! 😂 I guess because of recent API changes, this works again and is the solution. Thank you so much! 🙏🏼
